#! /bin/sh
#
# Author: liuling
#
# /etc/init.d/conveyor
#
#   and symbolic its link
#
# /usr/bin/rcconveyor
#
### BEGIN INIT INFO
# Provides: conveyor
# Required-Start: 
# Required-Stop: 
# Should-Start: 
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start the conveyor daemon
### END INIT INFO

CONVEYOR_BINS="/usr/bin/conveyor-api /usr/bin/conveyor-clone"
CONVEYOR_USER=openstack
CONVEYOR_ID=$(id -u $CONVEYOR_USER)
CONVEYOR_GID=$(id -g $CONVEYOR_USER)

. /etc/rc.status

# Shell functions sourced from /etc/rc.status:
#      rc_check         check and set local and overall rc status
#      rc_status        check and set local and overall rc status
#      rc_status -v     ditto but be verbose in local rc status
#      rc_status -v -r  ditto and clear the local rc status
#      rc_failed        set local and overall rc status to failed
#      rc_reset         clear local rc status (overall remains)
#      rc_exit          exit appropriate to overall rc status

function soft_stop () {
  for bin in $CONVEYOR_BINS ; do
    echo "Shutting down the listening $bin daemon"
    pkill -f "python $bin"
  done
}

function force_stop () {
  soft_stop
}

# First reset status of this service
rc_reset

case "$1" in
    start)
        echo -n "Starting SSH daemon"
        ## Start daemon with startproc(8). If this fails
        ## the echo return value is set appropriate.
        for bin in $CONVEYOR_BINS ; do
            #echo start-proc -u $CONVEYOR_ID -g $CONVEYOR_GID $bin --config-file /etc/conveyor/hybrid-v2v.conf 
            startproc -u $CONVEYOR_ID -g $CONVEYOR_GID $bin --config-file /etc/conveyor/hybrid-v2v.conf >/dev/null 2>&1
        done
      
        # Remember status and be verbose
        rc_status -v
        ;;
    stop)
        # If we're shutting down, kill active conveyor connections so they're not
        # left hanging.
        runlevel=$(set -- $(runlevel); eval "echo \$$#")
        if [ "x$runlevel" = x0 -o "x$runlevel" = x6 ] ; then
            force_stop
        else
            soft_stop
        fi
        
        # Remember status and be verbose
        rc_status -v
        ;;
    soft-stop)
        ## Stop the listener daemon process with killproc(8) and if this
        ## fails set echo the echo return value.
        soft_stop

        # Remember status and be verbose
        rc_status -v
        ;;
    force-stop)
        ## stop all running ssh
        force_stop

        # Remember status and be verbose
        rc_status -v
        ;;
    try-restart)
        ## Stop the service and if this succeeds (i.e. the 
        ## service was running before), start it again.
        $0 status >/dev/null &&  $0 restart

        # Remember status and be quiet
        rc_status
        ;;
    restart)
        ## Stop the service without closing live connections 
        ## and start it again regardless of whether it was
        ## running or not
        $0 soft-stop
        $0 start

        # Remember status and be quiet
        rc_status
        ;;
    force-reload|reload)
        ## Signal the daemon to reload its config. Most daemons
        ## do this on signal 1 (SIGHUP).
        echo -n "Reload service conveyor"

        rc_status -v

        ;;
    status)
        echo -n "Checking for service conveyor "
        ## Check status with checkproc(8), if process is running
        ## checkproc will return with exit status 0.

        # Status has a slightly different for the status command:
        # 0 - service running
        # 1 - service dead, but /var/run/  pid  file exists
        # 2 - service dead, but /var/lock/ lock file exists
        # 3 - service not running

       __rc=
       for bin in $CONVEYOR_BINS ; do 
         pgrep -fl "python $bin" >/dev/null|| { __rc=0; break; }
       done
       [ 0$__rc = 0 ]

        rc_status -v
        ;;
    *)
        echo "Usage: $0 {start|stop|soft-stop|force-stop|status|try-restart|restart|force-reload|reload}"
        exit 1
        ;;
esac
rc_exit
